carmandu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('dashboard/', include('dashboard.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = format_suffix_patterns(urlpatterns)

dashboard/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'dashboard'
urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),

    # Brand
    path('dashboard/brand/list/', BrandListView.as_view(), name='brands'),
    path('dashboard/brand/create/', BrandCreateView.as_view(), name='brand-create'),
    path('dashboard/brand/<int:pk>/update/',
         BrandUpdateView.as_view(), name='brand-update'),
    path('dashboard/brand/<int:pk>/delete/', BrandDeleteView.as_view(), name='brand-delete'),

    # model
    path('dashboard/model/list/', ModelListView.as_view(), name='models'),
    path('dashboard/model/create/', ModelCreateView.as_view(), name='model-create'),
    path('dashboard/model/<int:pk>/update/',
             ModelUpdateView.as_view(), name='model-update'),
    path('dashboard/model/<int:pk>/delete/', ModelDeleteView.as_view(), name='model-delete'),

    # type
    path('dashboard/type/list/', TypeListView.as_view(), name='types'),
    path('dashboard/type/create/',  TypeCreateView.as_view(), name='type-create'),
    path('dashboard/type/<int:pk>/update/',
              TypeUpdateView.as_view(), name='type-update'),
    path('dashboard/type/<int:pk>/delete/',  TypeDeleteView.as_view(), name='type-delete'),


    # features
    path('dashboard/features/list/', FeatureListView.as_view(), name='features'),
    path('dashboard/features/create/',  FeatureCreateView.as_view(), name='feature-create'),
    path('dashboard/features/<int:pk>/update/',
              FeatureUpdateView.as_view(), name='feature-update'),
    path('dashboard/features/<int:pk>/delete/',  FeatureDeleteView.as_view(), name='feature-delete'),

    # Cars
    path('dashboard/cars/list/', CarListView.as_view(), name='cars'),
    path('dashboard/cars/create/', CarCreateView.as_view(), name='cars-create'),
    path('dashboard/cars/<int:pk>/update/',
         CarUpdateView.as_view(), name='cars-update'),
    path('dashboard/cars/<int:pk>/delete/', CarDeleteView.as_view(), name='cars-delete'),
    path('dashboard/cars/image/create/', CarImageCreateView.as_view(), name='cars-image-create'),

    # about
    path('dashboard/about/list/', AboutListView.as_view(), name='abouts'),
    path('dashboard/about/create/',  AboutCreateView.as_view(), name='about-create'),
    path('dashboard/about/<int:pk>/update/',
              AboutUpdateView.as_view(), name='about-update'),
    path('dashboard/about/<int:pk>/delete/',  AboutDeleteView.as_view(), name='about-delete'),

    # team
    path('dashboard/team/list/', TeamListView.as_view(), name='teams'),
    path('dashboard/team/create/',  TeamCreateView.as_view(), name='team-create'),
    path('dashboard/team/<int:pk>/update/',
              TeamUpdateView.as_view(), name='team-update'),
    path('dashboard/team/<int:pk>/delete/',  TeamtDeleteView.as_view(), name='team-delete'),

    # services
    path('dashboard/services/list/', ServiceListView.as_view(), name='services'),
    path('dashboard/services/create/',  ServiceCreateView.as_view(), name='service-create'),
    path('dashboard/services/<int:pk>/update/',
              ServiceUpdateView.as_view(), name='service-update'),
    path('dashboard/services/<int:pk>/delete/',  ServiceDeleteView.as_view(), name='service-delete'),


    # services video
    path('dashboard/services-video/list/', ServiceVideoListView.as_view(), name='services-video'),
    path('dashboard/services-video/create/',  ServiceVideoCreateView.as_view(), name='service-video-create'),
    path('dashboard/services-video/<int:pk>/update/',
              ServiceVideoUpdateView.as_view(), name='service-video-update'),
    path('dashboard/services-video/<int:pk>/delete/',  ServiceVideoDeleteView.as_view(), name='service-video-delete'),


    # message
    path('dashboard/message/list/', MessageListView.as_view(), name='messages'),
    path('dashboard/message/<int:pk>/delete/',  MessageDeleteView.as_view(), name='message-delete'),


    # contact
    path('dashboard/contact/list/', ContactListView.as_view(), name='contacts'),
    path('dashboard/contact/create/',  ContactCreateView.as_view(), name='contact-create'),
    path('dashboard/contact/<int:pk>/update/',
              ContactUpdateView.as_view(), name='contact-update'),
    path('dashboard/contact/<int:pk>/delete/',  ContactDeleteView.as_view(), name='contact-delete'),

]

home/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('cars/', Carview.as_view(), name='cars'),
    path('about/',  AboutView.as_view(), name='about'),
    path('services/',  ServiceView.as_view(), name='services'),
    path('contact/', ContactView.as_view(), name='contact'),
]

dashboard/models.py
import datetime
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User, Group
from django.db import models
from django.db.models.enums import Choices
from django.utils import timezone
# Create your models here.

LOCATION = (
    ('Kathmandu','Kathmandu'),
    ('Bhaktapur', 'Bhaktapur'),
    ('Lalitpur', 'Lalitpur'),
)

COLOR = (
    ('Red', 'Red'),
    ('White', 'White'),
    ('Grey', 'Grey'),
    ('Black','Black'),
)

YEAR = (
    ('2015','2015'),
    ('2016','2016'),
    ('2017','2017'),
    ('2018','2018'),
    ('2019','2019'),
)

GENDER = (
    ('Male','Male'),
    ('Female','Female'),
    ('Others','Others'),
)

class DateTimeModel(models.Model):
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True

    def delete(self, hard=False):
        if not hard:
            self.deleted_at = timezone.now()
            return super().save()
        else:
            return super().delete()

class Account(User):
    mobile = models.CharField(max_length=250)
    address = models.CharField(max_length=250)
    image = models.ImageField(upload_to='user')

    class Meta:
        verbose_name = ('Account')
        verbose_name_plural = ('Accounts')
        ordering = ['username']

    def __str__(self):
        return self.username

# Customer Model


class Customer(User):
    GENDER = (('Male', 'Male'),
              ('Female', 'Female'),
              ('Others', 'Others'),)
    mobile = models.CharField(max_length=10)
    gender = models.CharField(max_length=10, choices = GENDER)
    is_customer = models.BooleanField(default=False)

    class Meta:
        verbose_name = ('Customer')
        verbose_name_plural = ('Customers')
        ordering = ['-username']

    def __str__(self):
        return self.first_name



class Brand(DateTimeModel):
    title = models.CharField(max_length=200)

    class Meta:
        verbose_name = ('Brand')
        verbose_name_plural = ('Brands')
        ordering = ['-title']

    def __str__(self):
        return self.title

class Model(DateTimeModel):
    title = models.CharField(max_length=200)

    class Meta:
        verbose_name = ('Model')
        verbose_name_plural = ('Models')
        ordering = ['-title']

    def __str__(self):
        return self.title

class Type(DateTimeModel):
    title = models.CharField(max_length=200)

    class Meta:
        verbose_name = ('Type')
        verbose_name_plural = ('Types')
        ordering = ['-title']

    def __str__(self):
        return self.title



class Features(DateTimeModel):
    title = models.CharField(max_length=200)

    class Meta:
        verbose_name = ('Feature')
        verbose_name_plural = ('Features')
        ordering = ['-title']

    def __str__(self):
        return self.title

class Car(DateTimeModel):
    name = models.CharField(max_length=200)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    model = models.ForeignKey(Model, on_delete=models.CASCADE)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    features = models.ForeignKey(Features, on_delete=models.CASCADE)
    location = models.CharField(max_length=200, choices=LOCATION)
    year = models.CharField(max_length=200, choices=YEAR)
    color = models.CharField(max_length=200, choices=COLOR)
    transmission = models.CharField(max_length=200)
    image = models.ImageField(upload_to='cars')
    price = models.PositiveIntegerField()
    description = RichTextField()
    is_on_sale = models.BooleanField("On Sale", default=False)
    is_on_rent = models.BooleanField("On Rent", default=False)
    is_featured = models.BooleanField("Featured", default=False)

    class Meta:
        verbose_name = ('Car')
        verbose_name_plural = ('Cars')
        ordering = ['-name']

    def __str__(self):
        return self.name

class CarImage(DateTimeModel):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='cars/images/')
    
    class Meta:
        verbose_name = ('CarImage')
        verbose_name_plural = ('CarImages')

    def __str__(self):
        return self.car.name

class About(DateTimeModel):
    image = models.ImageField(upload_to='about')
    description = RichTextField()

    class Meta:
        verbose_name = ('About')
        verbose_name_plural = ('Abouts')

    def __str__(self):
        return self.description

class Team(DateTimeModel):
    name = models.CharField(max_length=200)
    designation = models.CharField(max_length=200)
    image = models.ImageField(upload_to='team')

    class Meta:
        verbose_name = ('Team')
        verbose_name_plural = ('Teams')
        ordering = ['-name']

    def __str__(self):
        return self.name


class Services(DateTimeModel):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='services')
    description = models.CharField(max_length=200)

    class Meta:
        verbose_name = ('Service')
        verbose_name_plural = ('Services')
        ordering = ['-title']

    def __str__(self):
        return self.title


class ServicesVideo(DateTimeModel):
    video = models.FileField(upload_to='servicevideo')
    description = RichTextField()

    class Meta:
        verbose_name = ('ServicesVideo')
        verbose_name_plural = ('ServicesVideos')


    def __str__(self):
        return self.description


class Message(DateTimeModel):
    full_name = models.CharField(max_length=200)
    email = models.EmailField()
    subject = models.TextField(max_length=500)
    phone = models.CharField(max_length=200)
    message = models.TextField(max_length=500)

    class Meta:
        verbose_name = ('Message')
        verbose_name_plural = ('Messages')

    def __str__(self):
        return self.full_name


class Contact(DateTimeModel):
    phone = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    fax = models.CharField(max_length=200)
    working_hours = models.CharField(max_length=200)

    class Meta:
        verbose_name = ('Contact')
        verbose_name_plural = ('Contacts')

    def __str__(self):
        return self.email

dashboard/forms.py
from django import forms
from .models import *
from .mixins import *

# brands
class BrandForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = Brand
        fields = "__all__"

# cars
class CarForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = Car
        fields = "__all__"
        def __init__(self, *args, **kwargs):
          super().__init__(*args, **kwargs)
          
          self.fields['features'].widget.attrs.update({
            'class': 'form-control select2 feature-select',
            'multiple': 'multiple'
          })
          self.fields['is_on_sale'].widget.attrs.update({
              'class': "control outlined control-checkbox checkbox-success"
          })
          self.fields['is_on_rent'].widget.attrs.update({
              'class': "control outlined control-checkbox checkbox-success"
          })
          self.fields['is_featured'].widget.attrs.update({
              'class': "control outlined control-checkbox checkbox-success"
          })
          self.fields['brand'].widget.attrs.update({
              'class': 'form-control select2'
          })
          self.fields['model'].widget.attrs.update({
              'class': 'form-control select2'
          })
          self.fields['type'].widget.attrs.update({
              'class': 'form-control select2'
          })
          self.fields['category'].widget.attrs.update({
              'class': 'form-control select2'
          })
          
       

# carimage
class CarImageForm(forms.ModelForm):
  class Meta:
    model = CarImage
    fields = '__all__'


# models
class ModelForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = Model
        fields = "__all__"


# types
class TypeForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = Type
        fields = "__all__"




# features
class FeatureForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = Features
        fields = "__all__"


# about
class AboutForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = About
        fields = "__all__"
        widgets = {
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control',
                'placeholder': 'choose image'
            })
        }

# team
class TeamForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = Team
        fields = "__all__"
        widgets = {
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control',
                'placeholder': 'choose image'
            })
        }

# services
class ServicesForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = Services
        fields = "__all__"
        widgets = {
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control',
                'placeholder': 'choose image'
            })
        }

# services-video
class ServicesVideoForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = ServicesVideo
        fields = "__all__"

# contact
class ContactForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = Contact
        fields = "__all__"
       

# messages
class MessageForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = Message
        fields = "__all__"

dashboard/templates/dashboard/cars/form.html
{% extends 'dashboard/base/base.html' %}
{% block title %} Our Cars {% endblock %}
{% load static %}
{% block style %}
<style>
{% include 'dashboard/documents/upload-file.css' %}
</style>
{% endblock %}
{% block content %}
<div style="padding:40px;" class="container">
    <h3 style="padding:20px;">Our Cars</h3>
     <form method="POST" enctype="multipart/form-data" style="margin:40px;">
                            {% csrf_token %}
                            {{ form.media }}

                            <div class="row form-group">
                                <div class="col-md-6 col-sm-12">
                                    <label for="exampleFormControlInput1">Car Name</label>
                                    {{ form.name }}
                                </div>
                            
                                <div class="col-md-6 col-sm-12">
                                    <label for="exampleFormControlInput1">Brand Name</label>
                                    {{ form.brand }}
                                </div>
                         
                                <div class="col-md-6 col-sm-12">
                                    <label for="exampleFormControlInput1">Model Name</label>
                                    {{ form.model }}
                                </div>
                      
                                <div class="col-md-6 col-sm-12">
                                    <label for="exampleFormControlInput1">Type Name</label>
                                    {{ form.type }}
                                </div>
                          
                                
                         
                                <div class="col-md-6 col-sm-12">
                                    <label for="exampleFormControlInput1">Features </label>
                                    {{ form.features }}
                                </div>
                            
                                <div class="col-md-6 col-sm-12">
                                    <label for="exampleFormControlInput1">Location</label>
                                    {{ form.location }}
                                </div>
                         
                                <div class="col-md-6 col-sm-12">
                                    <label for="exampleFormControlInput1">Year</label>
                                    {{ form.year }}
                                </div>
                           
                                <div class="col-md-6 col-sm-12">
                                    <label for="exampleFormControlInput1">Color</label>
                                    {{ form.color }}
                                </div>
                        
                                <div class="col-md-6 col-sm-12">
                                    <label for="exampleFormControlInput1">Transmission</label>
                                    {{ form.transmission }}
                                </div>
                            
                                <div class="col-md-6 col-sm-12">
                                    <label for="exampleFormControlInput1">Image</label>
                                      {{form.image}}
                                </div>
                           
                                <div class="col-md-6 col-sm-12">
                                    <label for="exampleFormControlInput1">Price</label>
                                    {{ form.price }}
                                </div>
                           
                                <div class="col-md-3 col-sm-3">
                                    <label for="exampleFormControlInput1">Description</label>
                                    {{ form.description }}
                                </div>
                             </div>
                                <div class="col-md-6 col-sm-12">
                                    <label for="exampleFormControlInput1">On Sale</label>
                                    {{ form.is_on_sale }}
                                </div>
                          
                                <div class="col-md-6 col-sm-12" >
                                    <label for="exampleFormControlInput1">On Rent</label>
                                    {{ form.is_on_rent }}
                                </div>
                         
                                <div class="col-md-6 col-sm-12">
                                    <label for="exampleFormControlInput1">Featured</label>
                                    {{ form.is_featured }}
                                </div>
                           


                            
                                <button type="submit" class="btn btn-primary btn-default">Submit</button>
                                <a href="{% url 'dashboard:cars' %}" class="btn btn-secondary btn-default">Cancel</a>
                            
                        </form>
</div>

{% endblock %}
{% block script %}
<script>
{% include 'dashboard/documents/upload-file.js' %}
</script>
<script>
    $("#id_type").change(function () {
      var url = $("#category_form").attr("data-related-category");  // get the url of the `load_cities` view
      var TypeId = $(this).val();  // get the selected country ID from the HTML input
  
      $.ajax({                       // initialize an AJAX request
        url: url, 
        method:'GET',                   // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'type': TypeId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_categories").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });
  
    });
  </script>
{% endblock %}

dashboard/templates/dashboard/cars/imageform.html
<script> 
    isSubmitting = false;
    
    $('form').submit(function(){
        isSubmitting = true;
    });

    window.onbeforeunload = function() {
        if(!isSubmitting)
            return "Do you really want to leave this page ?";
    };
</script>

dashboard/templates/dashboard/cars/list.html
{% extends 'dashboard/base/base.html' %}
{% block title %} Cars {% endblock %}
{% load static %}
{% block content %}
<section id="main-content">
  <section class="wrapper">
    <div class="row">
      <div class="col-lg-9 main-chart">
        <!--CUSTOM CHART START -->
        <div class="border-head">
          <h3>Our Cars</h3>
          <a href="{% url 'dashboard:cars-create' %}" type="button" class="mb-1 btn btn-outline-primary">Add Cars</a>
        </div>
        <div class="card-body">
                        <table class="table table-hover ">
                            <thead>
                                <tr>
                                    <th scope="col">S.N</th>
                                    <th scope="col" width='25%'>Name</th>
                                    <th scope="col" width='25%'>Brand</th>
                                    <th scope="col" width='25%'>Model</th>
                                    <th scope="col" width='25%'>Type</th>
                                    <th scope="col" width='25%'>category</th>

                                    <th scope="col" width='25%'>Location</th>
                                    <th scope="col" width='25%'>Year</th>
                                   
                  
                             
                                    <th width='20%'>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for cars in object_list %}
                                <tr>
                                    <td scope="row">{{ forloop.counter }}</td>
                                    <td>{{ cars.name }}</td>
                                    <td>{{ cars.brand }}</td>
                                    <td>{{ cars.model }}</td>
                                    <td>{{ cars.type }}</td>
                                    <td>{{ cars.category }}</td>
                             
                                    <td>{{ cars.location }}</td>
                           
                                    <td>{{ cars.price }}</td>
                                 
                                   
                                    <td>
                                        <span>
                                            <a href="{% url 'dashboard:cars-update' cars.pk %}" class="btn btn-sm btn-success"><span class ="mdi mr-1 mdi-square-edit-outline">Edit</span></a>
                                        </span>
                                        <span>
                                            <a href="{% url 'dashboard:cars-delete' cars.pk %}" class="btn btn-sm btn-danger delete"><span class ="mdi mr-1 mdi-trash-can">Delete</span></a>
                                        </span>

                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>


    </div>
    </div>
    <!-- /row -->
  </section>
</section>
{% block script %}
<script>
$('.delete').click(function(e) {
        e.preventDefault();
        swal({
                title: "Are you sure?",
                text: "It will permanently deleted !",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                    window.location.href = $(this).attr('href');
                    swal(" 'Your file has been deleted.'!", {
                        icon: "success",
                    });
                }
            });
    })
</script>
{% endblock %}
{% endblock %}

dashboard/templates/dashboard/cars/upload-image.html
<div class="upload-box">
    <input class="upload-box-file" type="file" multiple accept="image/*">
    <select class="upload-file-select" name="image" multiple style="display:none;"></select>
    <div class="form-group upload-box-input text-center">
        <div class="upload-box-label" for="file"><i class="fa fa-cloud"></i> &nbsp;&nbsp; <strong>Choose a file</strong><span class="upload-box-dragndrop"> or drag it here</span>.</div>
        <div class="upload-files-list">
            <!-- File list here -->
            {% for file in object.image.all %}
                <div class="upload-file-content" data-pk="{{ file.pk }}">
                    <div class="upload-file-preview upload-image-preview">
                        <div class="upload-image">
                            <img src="{{ file.image.url }}">
                        </div>
                        <div class="upload-file-details">
                            <div class="upload-file-size"><strong>{{ file.file_size }}</strong> {{file.file_type}}</div>
                            <div class="upload-file-name"><span>{{ file.imagename|slice:'9:' }}</span></div>
                        </div>
                        <div class="upload-error" style="display: none;">
                            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="exclamation-triangle" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" class="svg-inline--fa fa-exclamation-triangle fa-w-18 fa-2x">
                                <path fill="currentColor" d="M569.517 440.013C587.975 472.007 564.806 512 527.94 512H48.054c-36.937 0-59.999-40.055-41.577-71.987L246.423 23.985c18.467-32.009 64.72-31.951 83.154 0l239.94 416.028zM288 354c-25.405 0-46 20.595-46 46s20.595 46 46 46 46-20.595 46-46-20.595-46-46-46zm-43.673-165.346l7.418 136c.347 6.364 5.609 11.346 11.982 11.346h48.546c6.373 0 11.635-4.982 11.982-11.346l7.418-136c.375-6.874-5.098-12.654-11.982-12.654h-63.383c-6.884 0-12.356 5.78-11.981 12.654z" class=""></path>
                            </svg>
                        </div>
                    </div>
                    <a href="#" class="upload-file-remove">Remove file</a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>