carmandu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('dashboard/', include('dashboard.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = format_suffix_patterns(urlpatterns)

dashboard/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'dashboard'
urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),

    # Brand
    path('dashboard/brand/list/', BrandListView.as_view(), name='brands'),
    path('dashboard/brand/create/', BrandCreateView.as_view(), name='brand-create'),
    path('dashboard/brand/<int:pk>/update/',
         BrandUpdateView.as_view(), name='brand-update'),
    path('dashboard/brand/<int:pk>/delete/', BrandDeleteView.as_view(), name='brand-delete'),

    # model
    path('dashboard/model/list/', ModelListView.as_view(), name='models'),
    path('dashboard/model/create/', ModelCreateView.as_view(), name='model-create'),
    path('dashboard/model/<int:pk>/update/',
             ModelUpdateView.as_view(), name='model-update'),
    path('dashboard/model/<int:pk>/delete/', ModelDeleteView.as_view(), name='model-delete'),

    # type
    path('dashboard/type/list/', TypeListView.as_view(), name='types'),
    path('dashboard/type/create/',  TypeCreateView.as_view(), name='type-create'),
    path('dashboard/type/<int:pk>/update/',
              TypeUpdateView.as_view(), name='type-update'),
    path('dashboard/type/<int:pk>/delete/',  TypeDeleteView.as_view(), name='type-delete'),


    # features
    path('dashboard/features/list/', FeatureListView.as_view(), name='features'),
    path('dashboard/features/create/',  FeatureCreateView.as_view(), name='feature-create'),
    path('dashboard/features/<int:pk>/update/',
              FeatureUpdateView.as_view(), name='feature-update'),
    path('dashboard/features/<int:pk>/delete/',  FeatureDeleteView.as_view(), name='feature-delete'),

    # Cars
    path('dashboard/cars/list/', CarListView.as_view(), name='cars'),
    path('dashboard/cars/create/', CarCreateView.as_view(), name='cars-create'),
    path('dashboard/cars/<int:pk>/update/',
         CarUpdateView.as_view(), name='cars-update'),
    path('dashboard/cars/<int:pk>/delete/', CarDeleteView.as_view(), name='cars-delete'),
    path('dashboard/cars/image/create/', CarImageCreateView.as_view(), name='cars-image-create'),

    # about
    path('dashboard/about/list/', AboutListView.as_view(), name='abouts'),
    path('dashboard/about/create/',  AboutCreateView.as_view(), name='about-create'),
    path('dashboard/about/<int:pk>/update/',
              AboutUpdateView.as_view(), name='about-update'),
    path('dashboard/about/<int:pk>/delete/',  AboutDeleteView.as_view(), name='about-delete'),

    # team
    path('dashboard/team/list/', TeamListView.as_view(), name='teams'),
    path('dashboard/team/create/',  TeamCreateView.as_view(), name='team-create'),
    path('dashboard/team/<int:pk>/update/',
              TeamUpdateView.as_view(), name='team-update'),
    path('dashboard/team/<int:pk>/delete/',  TeamtDeleteView.as_view(), name='team-delete'),

    # services
    path('dashboard/services/list/', ServiceListView.as_view(), name='services'),
    path('dashboard/services/create/',  ServiceCreateView.as_view(), name='service-create'),
    path('dashboard/services/<int:pk>/update/',
              ServiceUpdateView.as_view(), name='service-update'),
    path('dashboard/services/<int:pk>/delete/',  ServiceDeleteView.as_view(), name='service-delete'),


    # services video
    path('dashboard/services-video/list/', ServiceVideoListView.as_view(), name='services-video'),
    path('dashboard/services-video/create/',  ServiceVideoCreateView.as_view(), name='service-video-create'),
    path('dashboard/services-video/<int:pk>/update/',
              ServiceVideoUpdateView.as_view(), name='service-video-update'),
    path('dashboard/services-video/<int:pk>/delete/',  ServiceVideoDeleteView.as_view(), name='service-video-delete'),


    # message
    path('dashboard/message/list/', MessageListView.as_view(), name='messages'),
    path('dashboard/message/<int:pk>/delete/',  MessageDeleteView.as_view(), name='message-delete'),


    # contact
    path('dashboard/contact/list/', ContactListView.as_view(), name='contacts'),
    path('dashboard/contact/create/',  ContactCreateView.as_view(), name='contact-create'),
    path('dashboard/contact/<int:pk>/update/',
              ContactUpdateView.as_view(), name='contact-update'),
    path('dashboard/contact/<int:pk>/delete/',  ContactDeleteView.as_view(), name='contact-delete'),

]

home/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('cars/', Carview.as_view(), name='cars'),
    path('about/',  AboutView.as_view(), name='about'),
    path('services/',  ServiceView.as_view(), name='services'),
    path('contact/', ContactView.as_view(), name='contact'),
]

dashboard/forms.py
from django import forms
from .models import *
from .mixins import *

# brands
class BrandForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = Brand
        fields = "__all__"

# cars
class CarForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = Car
        fields = "__all__"
        def __init__(self, *args, **kwargs):
          super().__init__(*args, **kwargs)
          
          self.fields['features'].widget.attrs.update({
            'class': 'form-control select2 feature-select',
            'multiple': 'multiple'
          })
          self.fields['is_on_sale'].widget.attrs.update({
              'class': "control outlined control-checkbox checkbox-success"
          })
          self.fields['is_on_rent'].widget.attrs.update({
              'class': "control outlined control-checkbox checkbox-success"
          })
          self.fields['is_featured'].widget.attrs.update({
              'class': "control outlined control-checkbox checkbox-success"
          })
          self.fields['brand'].widget.attrs.update({
              'class': 'form-control select2'
          })
          self.fields['model'].widget.attrs.update({
              'class': 'form-control select2'
          })
          self.fields['type'].widget.attrs.update({
              'class': 'form-control select2'
          })
          self.fields['category'].widget.attrs.update({
              'class': 'form-control select2'
          })
          
       

# carimage
class CarImageForm(forms.ModelForm):
  class Meta:
    model = CarImage
    fields = '__all__'


# models
class ModelForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = Model
        fields = "__all__"


# types
class TypeForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = Type
        fields = "__all__"




# features
class FeatureForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = Features
        fields = "__all__"


# about
class AboutForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = About
        fields = "__all__"
        widgets = {
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control',
                'placeholder': 'choose image'
            })
        }

# team
class TeamForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = Team
        fields = "__all__"
        widgets = {
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control',
                'placeholder': 'choose image'
            })
        }

# services
class ServicesForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = Services
        fields = "__all__"
        widgets = {
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control',
                'placeholder': 'choose image'
            })
        }

# services-video
class ServicesVideoForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = ServicesVideo
        fields = "__all__"

# contact
class ContactForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = Contact
        fields = "__all__"
       

# messages
class MessageForm(FormControlMixin, forms.ModelForm):
      class Meta:
        model = Message
        fields = "__all__"

dashboard/views.py
from django.http import JsonResponse
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import *
from .forms import *
from .mixins import *
# Create your views here.

class DashboardView(TemplateView):
    template_name = 'dashboard/base/index.html'

# brands
class BrandListView(NonDeletedListMixin,ListView):
    template_name = 'dashboard/brand/list.html'
    model = Brand

    def get_queryset(self):
        queryset = super().get_queryset()
        if "title" in self.request.GET:
            if self.request.GET.get('title') != '':
                queryset = queryset.filter(
                    name__contains=self.request.GET.get("title"))
        return queryset


class BrandCreateView(CreateView):
    template_name = 'dashboard/brand/form.html'
    form_class = BrandForm
    success_url = reverse_lazy('dashboard:brands')


class BrandUpdateView(UpdateView):
    template_name = 'dashboard/brand/form.html'
    model = Brand
    form_class = BrandForm
    success_url = reverse_lazy('dashboard:brands')


class BrandDeleteView(DeleteMixin, DeleteView):
    model = Brand
    success_url = reverse_lazy('dashboard:brands')


# models
class ModelListView(NonDeletedListMixin,ListView):
    template_name = 'dashboard/model/list.html'
    model = Model

    def get_queryset(self):
        queryset = super().get_queryset()
        if "title" in self.request.GET:
            if self.request.GET.get('title') != '':
                queryset = queryset.filter(
                    name__contains=self.request.GET.get("title"))
        return queryset


class ModelCreateView(CreateView):
    template_name = 'dashboard/model/form.html'
    form_class = ModelForm
    success_url = reverse_lazy('dashboard:models')


class ModelUpdateView(UpdateView):
    template_name = 'dashboard/model/form.html'
    model = Model
    form_class = ModelForm
    success_url = reverse_lazy('dashboard:models')


class ModelDeleteView(DeleteMixin,DeleteView):
    model = Model
    success_url = reverse_lazy('dashboard:models')


# types
class TypeListView(NonDeletedListMixin,ListView):
    template_name = 'dashboard/type/list.html'
    model = Type

    def get_queryset(self):
        queryset = super().get_queryset()
        if "title" in self.request.GET:
            if self.request.GET.get('title') != '':
                queryset = queryset.filter(
                    name__contains=self.request.GET.get("title"))
        return queryset


class TypeCreateView(CreateView):
    template_name = 'dashboard/type/form.html'
    form_class = TypeForm
    success_url = reverse_lazy('dashboard:types')


class TypeUpdateView(UpdateView):
    template_name = 'dashboard/type/form.html'
    model = Type
    form_class = TypeForm
    success_url = reverse_lazy('dashboard:types')


class TypeDeleteView(DeleteMixin,DeleteView):
    model = Type
    success_url = reverse_lazy('dashboard:types')





# features
class FeatureListView(NonDeletedListMixin,ListView):
    template_name = 'dashboard/features/list.html'
    model = Features

    def get_queryset(self):
        queryset = super().get_queryset()
        if "title" in self.request.GET:
            if self.request.GET.get('title') != '':
                queryset = queryset.filter(
                    name__contains=self.request.GET.get("title"))
        return queryset


class FeatureCreateView(CreateView):
    template_name = 'dashboard/features/form.html'
    form_class = FeatureForm
    success_url = reverse_lazy('dashboard:features')


class FeatureUpdateView(UpdateView):
    template_name = 'dashboard/features/form.html'
    model = Features
    form_class = FeatureForm
    success_url = reverse_lazy('dashboard:features')


class FeatureDeleteView(DeleteMixin,DeleteView):
    model = Features
    success_url = reverse_lazy('dashboard:features')

# cars
class CarListView(NonDeletedListMixin,ListView):
    template_name = 'dashboard/cars/list.html'
    model = Car

    def get_queryset(self):
        queryset = super().get_queryset()
        if "name" in self.request.GET:
            if self.request.GET.get('name') != '':
                queryset = queryset.filter(
                    name__contains=self.request.GET.get("name"))
        return queryset

class CarImageCreateView(CreateView):
    model = CarImage
    form_class = CarImageForm
    template_name = "dashboard/car/imageform.html"

    def dispatch(self, request, *args, **kwargs):
        if self.request.is_ajax():
            return super().dispatch(request, *args, **kwargs)
        return JsonResponse({"error": "Cannot access this page"}, status=404)

    def form_valid(self, form):
        instance = form.save()
        return JsonResponse(
            {
                "status": "ok",
                "pk": instance.pk,
                "url": instance.image.url,
            }
        )

    def form_invalid(self, form):
        return JsonResponse({"errors": form.errors}, status=400)

class CarCreateView(CreateView):
    template_name = 'dashboard/cars/form.html'
    form_class = CarForm
    success_url = reverse_lazy('dashboard:cars')


class CarUpdateView(UpdateView):
    template_name = 'dashboard/cars/form.html'
    model = Car
    form_class = CarForm
    success_url = reverse_lazy('dashboard:cars')


class CarDeleteView(DeleteMixin, DeleteView):
    model = Car
    success_url = reverse_lazy('dashboard:cars')

# abouts
class AboutListView(NonDeletedListMixin,ListView):
    template_name = 'dashboard/about/list.html'
    model = About


class AboutCreateView(CreateView):
    template_name = 'dashboard/about/form.html'
    form_class = AboutForm
    success_url = reverse_lazy('dashboard:abouts')


class AboutUpdateView(UpdateView):
    template_name = 'dashboard/about/form.html'
    model = About
    form_class = AboutForm
    success_url = reverse_lazy('dashboard:abouts')


class AboutDeleteView(DeleteMixin,DeleteView):
    model = About
    success_url = reverse_lazy('dashboard:abouts')

# teams
class TeamListView(NonDeletedListMixin,ListView):
    template_name = 'dashboard/team/list.html'
    model = Team


class TeamCreateView(CreateView):
    template_name = 'dashboard/team/form.html'
    form_class = TeamForm
    success_url = reverse_lazy('dashboard:teams')


class TeamUpdateView(UpdateView):
    template_name = 'dashboard/team/form.html'
    model = Team
    form_class = TeamForm
    success_url = reverse_lazy('dashboard:teams')


class TeamtDeleteView(DeleteMixin,DeleteView):
    model = Team
    success_url = reverse_lazy('dashboard:teams')

# services
class ServiceListView(NonDeletedListMixin,ListView):
    template_name = 'dashboard/services/list.html'
    model = Services


class ServiceCreateView(CreateView):
    template_name = 'dashboard/services/form.html'
    form_class = ServicesForm
    success_url = reverse_lazy('dashboard:services')


class ServiceUpdateView(UpdateView):
    template_name = 'dashboard/services/form.html'
    model = Services
    form_class = ServicesForm
    success_url = reverse_lazy('dashboard:services')


class ServiceDeleteView(DeleteMixin,DeleteView):
    model = Services
    success_url = reverse_lazy('dashboard:services')


# services-video
class ServiceVideoListView(NonDeletedListMixin,ListView):
    template_name = 'dashboard/services-video/list.html'
    model = ServicesVideo


class ServiceVideoCreateView(CreateView):
    template_name = 'dashboard/services-video/form.html'
    form_class = ServicesVideoForm
    success_url = reverse_lazy('dashboard:services-video')


class ServiceVideoUpdateView(UpdateView):
    template_name = 'dashboard/services-video/form.html'
    model = ServicesVideo
    form_class = ServicesVideoForm
    success_url = reverse_lazy('dashboard:services-video')


class ServiceVideoDeleteView(DeleteMixin,DeleteView):
    model = ServicesVideo
    success_url = reverse_lazy('dashboard:services-video')

# contact
class ContactListView(NonDeletedListMixin,ListView):
    template_name = 'dashboard/contact/list.html'
    model = Contact


class ContactCreateView(CreateView):
    template_name = 'dashboard/contact/form.html'
    form_class = ContactForm
    success_url = reverse_lazy('dashboard:contacts')


class ContactUpdateView(UpdateView):
    template_name = 'dashboard/contact/form.html'
    model = Contact
    form_class = ContactForm
    success_url = reverse_lazy('dashboard:contacts')


class ContactDeleteView(DeleteMixin,DeleteView):
    model = Contact
    success_url = reverse_lazy('dashboard:contacts')


# message
class MessageListView(NonDeletedListMixin,ListView):
    template_name = 'dashboard/message/list.html'
    model = Message

class MessageDeleteView(DeleteMixin,DeleteView):
    model = Message
    success_url = reverse_lazy('dashboard:messages')

dashboard/templates/dashboard/features/form.html
{% extends 'dashboard/base/base.html' %}
{% block title %} Our Features {% endblock %}
{% load static %}
{% block content %}
<section id="main-content">
  <section class="wrapper">
    <div class="row">
      <div class="col-lg-9 main-chart">
        <!--CUSTOM CHART START -->
        <div class="border-head">
          <h3>Our Features</h3>

        </div>
        <div class="row">
             <div class="col-12" style="padding:20px;">
                <div class="card card-default" style="padding:20px;">
                    <div class="card-header card-header-border-bottom">
                        <h2>Basic Form Controls</h2>
                    </div>
                    <div class="card-body">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.media }}

                            <div class="row form-group">
                                <div class="col-md-6 col-sm-12">
                                    <label for="exampleFormControlInput1">Feature Name</label>
                                    {{ form.title }}
                                </div>
                            </div>

                            <div class="form-footer pt-4 pt-5 mt-4 border-top">
                                <button type="submit" class="btn btn-primary btn-default">Submit</button>
                                <a href="{% url 'dashboard:features' %}" class="btn btn-secondary btn-default">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
    </div>
    <!-- /row -->
  </section>
</section>

{% endblock %}

dashboard/templates/dashboard/features/list.html
{% extends 'dashboard/base/base.html' %}
{% block title %} Feature {% endblock %}
{% load static %}
{% block content %}
<section id="main-content">
  <section class="wrapper">
    <div class="row">
      <div class="col-lg-9 main-chart">
        <!--CUSTOM CHART START -->
        <div class="border-head">
          <h3>Our Categories</h3>
          <a href="{% url 'dashboard:feature-create' %}" type="button" class="mb-1 btn btn-outline-primary">Add Feature</a>
        </div>
        <div class="card-body">
                        <table class="table table-hover ">
                            <thead>
                                <tr>
                                    <th scope="col">S.N</th>
                                    <th scope="col" width='25%'>Name</th>
                                    <th width='20%'>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for feature in object_list %}
                                <tr>
                                    <td scope="row">{{ forloop.counter }}</td>
                                    <td>{{ feature.title }}</td>

                                    <td>
                                        <span>
                                            <a href="{% url 'dashboard:feature-update' feature.pk %}" class="btn btn-sm btn-success"><span class ="mdi mr-1 mdi-square-edit-outline">Edit</span></a>
                                        </span>
                                        <span>
                                            <a href="{% url 'dashboard:feature-delete' feature.pk %}" class="btn btn-sm btn-danger delete"><span class ="mdi mr-1 mdi-trash-can">Delete</span></a>
                                        </span>

                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>


    </div>
    </div>
    <!-- /row -->
  </section>
</section>
{% block script %}
<script>
$('.delete').click(function(e) {
        e.preventDefault();
        swal({
                title: "Are you sure?",
                text: "It will permanently deleted !",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                    window.location.href = $(this).attr('href');
                    swal(" 'Your file has been deleted.'!", {
                        icon: "success",
                    });
                }
            });
    })
</script>
{% endblock %}
{% endblock %}